/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    ChatComposer: typeof import('./src/components/ChatComposer.vue')['default']
    ChatEmpty: typeof import('./src/components/ChatEmpty.vue')['default']
    ChatSidebar: typeof import('./src/components/ChatSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UAlert: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCollapsible: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue')['default']
    UDashboardGroup: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardNavbar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/DashboardNavbar.vue')['default']
    UDashboardPanel: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardSidebar: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarCollapse: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/DashboardSidebarCollapse.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFileUpload: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    USkeleton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_203eb11119ceb084afa11fa032f291a3/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
  }
}
